auth:
  registry.hub.docker.com:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_PASSWORD }}
images:
  k8s.gcr.io/sig-storage/csi-attacher: willdockerhub/csi-attacher
  k8s.gcr.io/sig-storage/csi-provisioner: willdockerhub/csi-provisioner
  k8s.gcr.io/sig-storage/csi-node-driver-registrar: willdockerhub/csi-node-driver-registrar
  k8s.gcr.io/sig-storage/csi-resizer: willdockerhub/csi-resizer
  k8s.gcr.io/sig-storage/csi-snapshotter: willdockerhub/csi-snapshotter
  
