auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  gcr.io/google-containers/kube-apiserver: gcr4cn/google-containers/kube-apiserver
  #gcr.io/google-containers/kube-proxy: DOCKERHUB_USERNAME/google-containers/kube-proxy
  #gcr.io/google-containers/kube-controller-manager: DOCKERHUB_USERNAME/google-containers/kube-controller-manager
  #gcr.io/google-containers/kube-scheduler: DOCKERHUB_USERNAME/google-containers/kube-scheduler
  #gcr.io/google_containers/cluster-proportional-autoscaler-amd64: DOCKERHUB_USERNAME/google_containers/cluster-proportional-autoscaler-amd64
  #gcr.io/google-containers/pause: DOCKERHUB_USERNAME/google-containers/pause
  #gcr.io/google_containers/pause-amd64: DOCKERHUB_USERNAME/google_containers/pause-amd64

