auth:
  registry.hub.docker.com:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_PASSWORD }}
images:
  gcr.io/google-containers/kube-apiserver: gcr4cn/google-containers-kube-apiserver


